name: mark_jinxiaoman
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  permission_handler: ^11.2.0
  rxdart: ^0.27.7
  event_bus: ^2.0.0
  flutter_easyrefresh: ^2.2.2
  fluttertoast: ^8.2.6
  get: ^4.6.6
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  common_utils: ^2.1.0
  flutter_inappwebview: 6.0.0
  flutter_screenutil: ^5.9.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.5
  logger: ^2.3.0
  appwrite: ^12.0.4
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.0
  retrofit_generator: ^7.0.8
  json_serializable: ^6.6.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/google_fonts/inter/
    - assets/google_fonts/poppins/
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/google_fonts/poppins/Poppins-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/google_fonts/inter/Inter-Regular.ttf

